language: python
python:
  - "3.7"
  - "3.8-dev"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source backee -m unittest discover
after_success: 
  - coverage report
  - coveralls