name: build

on: 
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        python-version: ['3.8', '3.11']
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pip install coverage
        coverage run --source backee -m unittest discover

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
